---
# Deploy all the things!
- include: playbooks/create_watchtower_node.yml
- include: playbooks/create_ubuntu_webserver_node.yml
- include: playbooks/create_alpine_database_node.yml
- include: playbooks/create_windows_jumpbox_node.yml

- name: Get network information
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Get IP info
    debug:
      msg: 
        - "Watchtower deployed at: {{ watchtower.instance.ipv4 }}"
        - "Webserver deployed at: {{ webserver.instance.ipv4 }}"
        - "Database deployed at: {{ database.instance.ipv4 }}"
        - "Windows deployed at: {{ windows.instance.ipv4 }}"

# Configuring Watchtower node
#- include: playbooks/configure_watchtower_node.yml

# Configuring the individual nodes (Done by the Watchtower node)
#- include: playbooks/configure_ubuntu_webserver_node.yml
#- include: playbooks/configure_alpine_database_node.yml
#- include: playbooks/configure_windows_jumpbox_node.yml
