---
- name: pingwindows
  hosts: windows
  remote_user: "{{ user }}"
  become: yes
  become_user: "{{ user }}"
  become_method: runas
  gather_facts: yes
  vars_files:
    - vars-global.yml
  tasks:
    - win_ping:  
