---

# Install ADDS
- name: install-adds
  hosts: windows
  remote_user: student
  become: yes
  become_user: student
  become_method: runas
  gather_facts: yes
  tasks:
    - name: Installeer ADDS
      win_feature:
        name: AD-Domain-Services
        state: present
        include_sub_features: yes
        include_management_tools: yes
      register: win_feature
    
    - name: Installer DNS
      win_feature:
        name: DNS
        state: present
        include_sub_features: yes
        include_management_tools: yes
      register: win_feature
   
    - name: Herstart server wanneer dit nodig is voor het installeren van de rol/feature
      win_reboot:
      when: win_feature.reboot_required  
    
    - name: Herstart server
      win_reboot:

# Set DNS Localhost
- name: setup-dns-address
  hosts: windows
  remote_user: student
  become: yes
  become_user: student
  become_method: runas
  gather_facts: no
  tasks:
    - name: Stel DNS in op localhost en Google
      win_dns_client:
        adapter_names: 'Ethernet1'
        ipv4_addresses:
        - 127.0.0.1
        - 8.8.8.8
        log_path: c:\dns_log.txt

# Setup ADDS
- name: setup-adds
  hosts: windows
  remote_user: student
  become: yes
  become_user: student
  become_method: runas
  gather_facts: no
  tasks:
    - name: Maak een nieuw domein met een nieuw forest
      win_domain:
        dns_domain_name: ansible.local
        domain_netbios_name: WSRV-ADDS
        safe_mode_password: Password123!
      register: domain_result

    - name: Start netlogon service
      win_service:
        name: netlogon
        state: started

    - name: Herstart server wanneer dit nodig is voor het installeren van de rol/feature
      win_reboot:
      when: domain_result.reboot_required  
