---

- name: apache-install
  hosts: node1
  remote_user: student
  become: yes
  vars_files:
    - vars-apache.yml
  tasks:
    - name: Enable Apache headers mod
      command: sudo a2enmod headers

    # Edit apache2.conf
    - name: apache ServerSignature Off
      lineinfile:
        path: {{ apache-config-path }}
        regexp: "^ServerSignature"
        line: | 
          ServerSignature Off
          ServerTokens Prod
          Header set X-XSS-Protection "1; mode=block"
        insertafter: ""
        state: present
        backup: yes

    # Edit apache2.conf
    - name: apache Disable Directory Listing
      lineinfile:
        path: {{ apache-config-path }}
        insertbefore: '^#<Directory /srv/>'
        regexp: "^<Directory /var/www/html>"
        line: |
          <Directory /var/www/html>
              Options -Indexes
          </Directory>
    - name:  
    
    - name: restart apacheserver
      service:
        name: apache2
        state: restarted
