---

- name: changebash
  hosts: node1
  remote_user: "{{ user }}"
  become: true
  vars_files:
    - vars-general.yml
  tasks:
    - name: install fonts-powerline
      apt:
        name: fonts-powerline
        state: latest
    - name: backup old bashrc file
      copy:
        src: "{{ home_folder }}/.bashrc"
        dest: "{{ home_folder }}/.bashrc_originals"
        owner: "{{ user }}"
        group: sudo
        mode: "0644"
      register: copy_done    
    - name: get new bashrc from github
      get_url:
        url: https://gist.githubusercontent.com/KaMeHb-UA/7b12035f29dad630f13a63a3dd72d183/raw/ca3696ad44bb846bb8b57e59869c21c7dd77650a/.bashrc
        dest: "{{ home_folder }}/.bashrc"
      when: copy_done is skipped

