---
- name: checknano
  hosts: node1
  remote_user: "{{ user }}"
  become: true
  vars_files:
    - vars-general.yml
  tasks:
    - name: check if nano is installed
      apt:
        name: nano
        state: latest
   
