---

# Used modules
# https://docs.ansible.com/ansible/2.6/modules/docker_container_module.html
# https://docs.ansible.com/ansible/2.5/modules/file_module.html#file-module

- name: deploydocker
  hosts: linux
  remote_user: "{{ user }}"
  become: true
  vars_files:
    - vars-general.yml
    - vars-deploy-docker.yml
  tasks:
    # Create folders
    - name: create necessary folders
      file:
        path: "{{ make_folders }}"
        owner: "{{ user }}"
        group: sudo
        mode: '0755'
        state: directory

    # Create web network
    - name: create web network
      docker_network:
        name: "{{ network }}"      

    # Portainer
    - name: laungh portainer container
      docker_container:
        name: portainer
        image: portainer/portainer-ce
        restart_policy: unless-stopped
        detach: yes
        state: started
#        state: absent
        purge_networks: yes
        networks_cli_compatible: yes
        volumes: "{{ portainer_volumes }}"
        published_ports: "{{ portainer_ports }}"
        networks:
          - name: "{{ network }}"

    # Watchtower
    - name: laungh watchtower container
      docker_container:
        name: watchtower
        image: containrrr/watchtower:latest
        restart_policy: unless-stopped
        detach: yes
        state: started
#        state: absent
        purge_networks: yes
        networks_cli_compatible: yes
        volumes: "{{ watchtower_volumes }}"
        env:
          TZ: "{{ timezone }}"
          WATCHTOWER_POLL_INTERVAL: "3600"
          WATCHTOWER_INCLUDE_STOPPED: "true"
          WATCHTOWER_DEBUG: "true"
          WATCHTOWER_CLEANUP: "true"
          WATCHTOWER_NOTIFICATIONS: "shoutrrr"
          WATCHTOWER_NOTIFICATION_URL: "{{ watchtower_notfi_url }}"
          WATCHTOWER_MONITOR_ONLY: "true"
          WATCHTOWER_REVIVE_STOPPED: "true"
        networks:
          - name: "{{ network }}"

