---
- name: lininfile
  hosts: node1
  remote_user: "{{ username }}"
  become: true
  vars_files:
    - vars/lineinfile.yml
  tasks:
    - name: Plaats tekst in een bestand en controleer of deze al bestaat
      lineinfile:
        path: "{{ path }}"
#        regexp: "^ServerSignature Off\nServerTokens Prod\nHeader set X-XSS-Protection \"1; mode=block\""
        line: "{{ text }}"
        insertafter: ""
        state: present
        backup: yes
      check_mode: yes
#        ignore_errors: yes
#        changed_when: no

