---

- name: lampstack
  hosts: linux
  remote_user: "{{ user }}"
  become: true
  vars_files:
    - vars-general.yml
    - vars-deploy-lamp-stack.yml
  tasks:
    # Create folders
    - name: create necessary folders
      file:
        path: "{{ make_folders }}"
        owner: "{{ user }}"
        group: sudo
        mode: "0755"
        state: directory

    # Create web network
    - name: create lamp network
      docker_network:
        name: "{{ network }}"      

    # MariaDB
    - name: Deploy MariaDB database
      docker_container:
        name: mariadb
        image: mariadb:latest
        restart_policy: unless-stopped
        detach: yes
        state: started
#        state: absent
        purge_networks: yes
        networks_cli_compatible: yes
        volumes: "{{ mariadb_volumes }}"
        env:
          MYSQL_RANDOM_ROOT_PASSWORD: "yes"
          MYSQL_DATABASE: "{{ database }}"
          MYSQL_USER: "{{ database_user }}"
          MYSQL_PASSWORD: "{{ database_password }}"
        networks:
          - name: "{{ network }}"

    # Apache
    - name: Deploy Apache webserver
      docker_container:
        name: apache
        image: httpd:alpine
        restart_policy: unless-stopped
        detach: yes
        state: started
        links:
          - mariadb:mariadb
#        state: absent
        purge_networks: yes
        networks_cli_compatible: yes
        volumes: "{{ apache_volumes }}"
        published_ports: "{{ apache_ports }}"
        networks:
          - name: "{{ network }}"

    # PHPMyAdmin
    - name: Deploy PHPMyAdmin
      docker_container:
        name: phpmyadmin
        image: phpmyadmin:latest
        restart_policy: unless-stopped
        detach: yes
        state: started
#        state: absent
        links:
          - mariadb:mariadb
        purge_networks: yes
        networks_cli_compatible: yes
        published_ports: "{{ phpmyadmin_ports }}"
        env:
          PMA_ARBITRARY: "1"
          PMA_HOST: "mariadb"
          PMA_PORT: "3306"
          PMA_USER: "{{ phpmyadmin_user }}"
          PMA_PASSWORD: "{{ phpmyadmin_password }}"
          MYSQL_PASSWORD: "{{ MyPassword123 }}"
        networks:
          - name: "{{ network }}""

