---
- name: Windows Server node
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - seclab.yml
  tasks:
  - name: Deploy Windows Server node from Windows Server 2019 (1809) template
    vmware_guest:
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: False
      name: "{{ name_prefix }} Windows Server node"
      template: "{{ windows_template }}"
      datacenter: "{{ datacenter }}"
      datastore: "{{ datastore }}"
      folder: "{{ folder }}"
      resource_pool: "{{ resource_pool }}"
      state: present

  - name: Attach internet NIC to the virtual machine
    vmware_guest:
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: False
      name: "{{ name_prefix }} Windows Server node"
      template: "{{ windows_template }}"
      datacenter: "{{ datacenter }}"
      datastore: "{{ datastore }}"
      folder: "{{ folder }}"
      resource_pool: "{{ resource_pool }}"
      networks:
        - name: "{{ network_portgroup_inet }}"
          connected: yes
          ip: "192.168.56.178"
      state: present

  - name: Power on Virtual Machine
    vmware_guest:
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: False
      name: "{{ name_prefix }} Windows Server node"
      template: "{{ windows_template }}"
      datacenter: "{{ datacenter }}"
      datastore: "{{ datastore }}"
      folder: "{{ folder }}"
      resource_pool: "{{ resource_pool }}"
      networks:
        - name: "{{ network_portgroup_inet }}"
          connected: yes
          start_connected: yes
          ip: "192.168.56.178"          
      wait_for_ip_address: yes
      state: poweredon
    register: windows