---
- name: Database node
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - seclab.yml
  tasks:
  - name: Deploy database node from Linux Alpine template
    vmware_guest:
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: False
      name: "{{ name_prefix }} N2-DATABASE"
      template: "Templ_Alpine_Linux_3.13.2"
      datacenter: "{{ datacenter }}"
      datastore: "{{ datastore }}"
      folder: "{{ folder }}"
      resource_pool: "{{ resource_pool }}"
      state: present
