version: '3.7'
services:
  portainer:
    image: portainer/portainer-ce
    restart: unless-stopped
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - <path>:/data
    ports:
      - 8000:8000
      - 9000:9000
    networks:
      - web

networks:
  web:
    external:
      name: web
